---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  make-fc34:
    runs-on: ubuntu-latest
    container:
      image: fedora:34
    steps:
      - name: install dependencies
        run: |
          dnf -y install cmake kf5-ki18n-devel kf5-kcmutils-devel kf5-kdeclarative-devel qt5-qtsvg-devel kf5-plasma-devel qt5-qtmultimedia-devel kf5-rpm-macros
      - uses: actions/checkout@v2
      - name: compile kcm_webcam_settiugs
        run: |
          mkdir build
          cd build
          cmake ..
          make
  make-fc35:
    runs-on: ubuntu-latest
    container:
      image: fedora:35
    steps:
      - name: install dependencies
        run: |
          dnf -y install cmake kf5-ki18n-devel kf5-kcmutils-devel kf5-kdeclarative-devel qt5-qtsvg-devel kf5-plasma-devel qt5-qtmultimedia-devel kf5-rpm-macros
      - uses: actions/checkout@v2
      - name: compile kcm_webcam_settiugs
        run: |
          mkdir build
          cd build
          cmake ..
          make
  make-fc36:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      - name: install dependencies
        run: |
          dnf -y install cmake kf5-ki18n-devel kf5-kcmutils-devel kf5-kdeclarative-devel qt5-qtsvg-devel kf5-plasma-devel qt5-qtmultimedia-devel kf5-rpm-macros
      - uses: actions/checkout@v2
      - name: compile kcm_webcam_settiugs
        run: |
          mkdir build
          cd build
          cmake ..
          make
  code-analysis:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ GITHUB_HEAD_REF }}
