---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  make:
    strategy:
      max-parallel: 2
      matrix:
        fedora-release:
          - 34
          - 35
          - 36
    container:
      image: fedora:${{ fedora-release }}
    steps:
      - name: install dependencies
        run: |
          dnf install cmake kf5-ki18n-devel kf5-kcmutils-devel kf5-kdeclarative-devel qt5-qtsvg-devel kf5-plasma-devel qt5-qtmultimedia-devel kf5-rpm-macros
      - uses: actions/checkout@v2
      - name: compile kcm_webcam_settiugs
        run: |
          mkdir build
          cd build
          cmake ..
          make
